# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

version: 0.2

env:
  variables:
    APP: to-data-library

phases:

  install:
    on-failure: ABORT
    runtime-versions:
      python: 3.10
    commands:
    - pip install -r requirements.txt

  build:
    on-failure: ABORT
    commands:
    - pre-commit run --all-files
    - python -m unittest
