# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  -  id: trailing-whitespace
  -  id: end-of-file-fixer
  -  id: check-yaml
     args:
     - '--unsafe'
  -  id: detect-private-key
  -  id: no-commit-to-branch
  -  id: check-added-large-files
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.0
  hooks:
  - id: ruff-check
    args: [--fix]
  - id: ruff-format
- repo: https://github.com/sqlfluff/sqlfluff
  rev: 3.4.0
  hooks:
    - id: sqlfluff-lint
    - id: sqlfluff-fix
